import os
import sys
import glob
import frontmatter  # Parses and rewrites YAML front matter safely
import requests
import random

DRY_RUN = len(sys.argv) >= 2 and sys.argv[1] == "--dry-run"

# configuration
if not DRY_RUN:
    ACCESS_TOKEN = os.environ.get("LNKDIN_ACCESS_TOKEN")
    with open("linkedin_urn.config.txt") as f:
        AUTHOR_URN = f.read().strip()
        
SITE_URL = "https://tiash-and-cats.github.io"

ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
BOLD_ALPHABET = "𝗮𝗯𝗰𝗱𝗲𝗳𝗴𝗵𝗶𝗷𝗸𝗹𝗺𝗻𝗼𝗽𝗾𝗿𝘀𝘁𝘂𝘃𝘄𝘅𝘆𝘇𝗔𝗕𝗖𝗗𝗘𝗙𝗚𝗛𝗜𝗝𝗞𝗟𝗠𝗡𝗢𝗣𝗤𝗥𝗦𝗧𝗨𝗩𝗪𝗫𝗬𝗭𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵"
ITALIC_ALPHABET = "𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫"
BOLD_ITALIC_ALPHABET = "𝙖𝙗𝙘𝙙𝙚𝙛𝙜𝙝𝙞𝙟𝙠𝙡𝙢𝙣𝙤𝙥𝙦𝙧𝙨𝙩𝙪𝙫𝙬𝙭𝙮𝙯𝘼𝘽𝘾𝘿𝙀𝙁𝙂𝙃𝙄𝙅𝙆𝙇𝙈𝙉𝙊𝙋𝙌𝙍𝙎𝙏𝙐𝙑𝙒𝙓𝙔𝙕𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵"

BOLD_TRANS = {
    **str.maketrans(ALPHABET, BOLD_ALPHABET),
    **str.maketrans(ITALIC_ALPHABET, BOLD_ITALIC_ALPHABET),
    **str.maketrans(BOLD_ALPHABET, ALPHABET),
}
ITALIC_TRANS = {
    **str.maketrans(ALPHABET, ITALIC_ALPHABET),
    **str.maketrans(BOLD_ALPHABET, BOLD_ITALIC_ALPHABET),
    **str.maketrans(ITALIC_ALPHABET, ALPHABET),
}

if not DRY_RUN:
    if not ACCESS_TOKEN:
        print("\x1b[1;31mError: Missing LINKEDIN_ACCESS_TOKEN in Environment Secrets.\x1b[0m")
        sys.exit(1)

# look for all blog posts
post_files = glob.glob("_posts/*.md") + glob.glob("_posts/*.markdown")
if not post_files:
    print("No posts found in _posts/ directory.")
    sys.exit(0)

# find the newest markdown post by file creation/modification time
latest_post_path = max(post_files, key=os.path.getmtime)
print(f"Checking front matter for: {latest_post_path}")

# load the file layout
with open(latest_post_path, "r", encoding="utf-8") as f:
    post = frontmatter.load(f)

# conditional check: skip if explicitly marked false
# note: if the key is entirely missing, it defaults to True and executes
if not DRY_RUN:
    if post.get("post2lnkdin") is False:
        print(f"\x1b[23m>> Skipping. 'post2lnkdin: false' found in frontmatter.\x1b[0m")
        sys.exit(0)

    print("\x1b[1mNew post discovered! Preparing LinkedIn broadcast...\x1b[0m")

title = post.get("title", "New Blog Update")
description = post.get("description", post.content.split("\n\n", 1)[0])

# derive custom Jekyll permalink structure from file name
filename = os.path.basename(latest_post_path)
date_part = "-".join(filename.split("-")[:3])  # Extracts YYYY-MM-DD
title_part = "-".join(filename.split("-")[3:]).split(".")[0]
post_date_path = date_part.replace("-", "/")

# construct production hyperlink path
permalink = f"{SITE_URL}/{post_date_path}/{title_part}.html"

# format text
post_cta = random.choice([
    "🚀 New blog post is out!",
    "📖 Something new to read...",
    "✨ Fresh thoughts, just published!",
    "📝 Hot off the keyboard!",
    "🌐 Another adventure in code awaits...",
    "💡 A new idea to explore...",
    "🔥 Latest update — check it out!",
    "🎉 Fresh content, straight from Tiash!",
    "🔧 Tweaks, tips, and tales — live now!",
])

read_here_cta = random.choice([
    "Read it here:", "Check it out!"
])

formatted_text = f"""\
{post_cta.translate(BOLD_TRANS)}

{"Title:".translate(BOLD_TRANS)} {title}

{description}

{f"👉 {read_here_cta}".translate(BOLD_TRANS)} {permalink}\
"""

comment_text = f"{"Note:".translate(BOLD_TRANS)} Both the original post and this comment are generated by a Python script. You can find it here: {"https://github.com/tiash-and-cats/tiash-and-cats.github.io/blob/master/.github/scripts/linkedin_share.py".translate(ITALIC_TRANS)}. It simply checks the latest blog post and posts a notification in the form of a LinkedIn post. This process does not use AI.".translate(ITALIC_TRANS)

if not DRY_RUN:
    # execute LinkedIn REST API Request
    url = "https://api.linkedin.com/v2/ugcPosts"

    headers = {
        "Authorization": f"Bearer {ACCESS_TOKEN}",
        "X-Restli-Protocol-Version": "2.0.0",
        "Content-Type": "application/json",
    }

    payload = {
        "author": AUTHOR_URN,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {
                    "text": formatted_text
                },
                "shareMediaCategory": "NONE"
            }
        },
        "visibility": {
            "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
        }
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code == 201:
        post_id = response.json().get("id")
        print(f"\x1b[1;32mSuccessfully posted to LinkedIn! ID: {post_id}\x1b[0m")

        # Save tracking variables to markdown front matter
        post["post2lnkdin"] = False
        with open(latest_post_path, "w", encoding="utf-8") as f:
            frontmatter.dump(post, f, sort_keys=False)
        print(f"\x1b[1mAppended 'post2lnkdin: false' to {filename} natively.\x1b[0m")

        # Now post the follow-up comment
        comment_url = f"https://api.linkedin.com/rest/socialActions/{post_id}/comments"
        comment_payload = {
            "actor": AUTHOR_URN,
            "object": post_id,
            "message": {
                "text": comment_text
            }
        }

        comment_response = requests.post(comment_url, headers=headers, json=comment_payload)
        if comment_response.status_code == 201:
            print("\x1b[1;32mSuccessfully added disclaimer comment!\x1b[0m")
        else:
            print(f"\x1b[1;31mFailed to add comment: {comment_response.status_code}\n{comment_response.json()}\x1b[0m")
    else:
        print(f"\x1b[1;31mAPI Rejected Request: {response.status_code}\n{response.json()}\x1b[0m")
        sys.exit(1)
else:
    print(formatted_text)
    print(comment_text)